### PR TITLE
Stop invalid key notice

### PR DESCRIPTION
**Pull request by ddelrio1986**

### CODE REVIEW

**Comment by ddelrio1986** [comment]
Just wondering if you ever had time to look over this?

**Comment by justintadlock** [comment]
I probably haven't if there's not an issue posted.

**Comment by ddelrio1986** [comment]
So you want me to create an issue for it first?

**Comment by ddelrio1986** [comment]
I've already created a patch for the issue I ran into so I didn't see a need to create an issue for it. Instead I just wanted to share my patch with the main repository to help make it better.

**Comment by justintadlock** [comment]
Yeah, there'd need to be an issue before I'd consider any PRs for something.

**Comment by ddelrio1986** [comment]
Okay I'll create an issue then and link this PR to the issue.

**Comment by ddelrio1986** [comment]
I didn't see any CONTRIBUTING.md explaining the way you'd like people to contribute. I could create a PR for adding one to the repository so in the future people know that you want an issue for the PR instead of just a PR. Want me to do that?

**Comment by ddelrio1986** [comment]
Okay I've added an issue for it.

**Comment by ddelrio1986** [comment]
Let me know if you'd like me to create a PR that'll add a CONTRIBUTING.md that explains to others that you'd like an issue tied to any PR's so that others know in the future that you won't look at the PR unless it has an issue.

**Comment by ddelrio1986** [comment]
So did you have anytime to check this out?

**Comment by ddelrio1986** [comment]
Still maintaining this?

**Comment by lkraav** [comment]
I'm not familiar with the issue specifics (yet), but the PR should not contain the random `.gitignore` change.

**Comment by lkraav** [comment]
You also have clear whitespace error in the main improvement - tabs vs spaces.

**Comment by lkraav** [comment]
How does one arrive at the settings array getting desynced in the first place? Hiding this problem with a silencer might actually mask a deeper problem.

**Pull request closed without merging**
